### ISSUE TITLE
System.BadImageFormatException Error

### ISSUE THREAD

**Issue by sandyboxy** [hexfati/SharpDllLoader#2]
Hello,
I am trying to use your interesting tool to investigate DLL behavior, but when I run SharpDllLoader.exe by specifying parameters in this way `d "C:\Users\malicious.dll" -c <Class> -m <Method> -a "arg1 arg2 arg3"` I obtain the following error
```
An unhandled exception occurred in SharpDllLoader.exe (2360)

Exception: System.BadImageFormatException

Message: The file or assembly "malicious.dll" or one of its dependencies could not be loaded. it is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
```

**Comment by hexfati** [comment]
It's probably a problem with your 'malicious.dll' during the loading of the library.
