### ISSUE TITLE
Exception：System.IO.FileLoadException

### ISSUE THREAD

**Issue by kcufId** [hexfati/SharpDllLoader#3]
hello：
There was an error debugging the DLL：
Message： 
Mixed model assembly is aimed at "v2.0.50727" version of the runtime of the generated, in the absence of other configuration information, unable to load the assembly in the 4.0 runtime

However, there are configuration files(filename.config) in the same directory：
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<startup useLegacyV2RuntimeActivationPolicy="true">
<supportedRuntime version="v2.0.50727"/>
<supportedRuntime version ="v4.0"/>
</startup>
</configuration>

**Comment by bluecapone** [comment]
up, the same error happens to me
