### ISSUE TITLE
Handling "-" namespaces

### ISSUE THREAD

**Issue by luca-m** [hexfati/SharpDllLoader#5]
Hi,

How is possible to handle the "-" namespace ? (e.g. -n "-" ) 

It is common in packed malware and currently it is mis-parsed as "parameter name"

**Comment by hexfati** [comment]
Hi, when you have a class under "-" in dnSpy it means that there is no namespace. As shown below:
![image](https://user-images.githubusercontent.com/63205356/150355278-75583760-c514-4691-b9a1-6953f58e962d.png)

So, you can simply remove the -n parameter.
